const MAP_URL='https://upload.wikimedia.org/wikipedia/commons/3/31/Provinces_of_Japan.svg';
const RAW=[
['yamashiro','山城','やましろ','畿内','京都府南部',455,335,'平安京・京都を含む畿内の国。',''],['yamato','大和','やまと','畿内','奈良県',470,370,'古代国家の中心地。奈良盆地を中心とする。',''],['kawachi','河内','かわち','畿内','大阪府東部',440,375,'和泉・摂津とともに現在の大阪府域を分ける。',''],['izumi','和泉','いずみ','畿内','大阪府南西部',425,407,'河内から分立した国。泉州の名称にも残る。',''],['settsu','摂津','せっつ','畿内','大阪府北中部・兵庫県南東部',415,345,'大阪・神戸の双方にまたがる。',''],
['iga','伊賀','いが','東海道','三重県西部',505,355,'伊勢の西側。伊賀盆地を中心とする。',''],['ise','伊勢','いせ','東海道','三重県北中部',530,382,'伊勢神宮で知られる。',''],['shima','志摩','しま','東海道','三重県志摩半島',548,418,'志摩半島を中心とする小国。',''],['owari','尾張','おわり','東海道','愛知県西部',550,340,'名古屋周辺を含む。三河と対で覚える。',''],['mikawa','三河','みかわ','東海道','愛知県東部',590,345,'愛知県東部。尾張の東側。',''],['totomi','遠江','とおとうみ','東海道','静岡県西部',625,355,'難読国名。「遠つ淡海」に由来するとされる。',''],['suruga','駿河','するが','東海道','静岡県中部',665,350,'富士山南麓・駿河湾周辺。',''],['izu','伊豆','いず','東海道','静岡県伊豆半島・伊豆諸島',695,395,'伊豆半島のほか伊豆諸島も含む。',''],['kai','甲斐','かい','東海道','山梨県',610,310,'現在の山梨県にほぼ対応。',''],['sagami','相模','さがみ','東海道','神奈川県の大部分',650,335,'神奈川県の大部分。東側の一部は武蔵。',''],['musashi','武蔵','むさし','東海道','東京都・埼玉県・神奈川県東部',670,290,'東京・埼玉を中心とする大国。',''],['awa_kanto','安房','あわ','東海道','千葉県南部',720,365,'房総半島南部。「阿波」と同音なので注意。','awa'],['kazusa','上総','かずさ','東海道','千葉県中南部',730,330,'下総より南に位置する。「上」が京都に近い側。','so'],['shimousa','下総','しもうさ','東海道','千葉県北部・茨城県南西部',730,292,'上総の北側。現在の県境を越えて茨城県にも及ぶ。','so'],['hitachi','常陸','ひたち','東海道','茨城県の大部分',775,250,'難読国名。茨城県の大部分に対応。',''],
['omi','近江','おうみ','東山道','滋賀県',485,320,'琵琶湖を囲む。「近つ淡海」に由来するとされる。',''],['mino','美濃','みの','東山道','岐阜県南部',520,305,'岐阜県南部。飛騨と対で覚える。',''],['hida','飛騨','ひだ','東山道','岐阜県北部',540,270,'岐阜県北部の山地。',''],['shinano','信濃','しなの','東山道','長野県',585,265,'現在の長野県にほぼ対応。',''],['kozuke','上野','こうずけ','東山道','群馬県',630,250,'難読。「上毛（じょうもう）」の名称にもつながる。','no'],['shimotsuke','下野','しもつけ','東山道','栃木県',680,240,'上野と対。現在の栃木県にほぼ対応。','no'],['mutsu','陸奥','むつ','東山道','東北地方太平洋側を中心とする広域',750,80,'時代により範囲が変化する非常に広い国。',''],['dewa','出羽','でわ','東山道','山形県・秋田県を中心とする地域',680,115,'山形・秋田を中心とする。後世に羽前・羽後へ分かれた。',''],
['wakasa','若狭','わかさ','北陸道','福井県南部',478,280,'若狭湾沿岸。越前とともに福井県域を構成。',''],['echizen','越前','えちぜん','北陸道','福井県北部',510,250,'越前・越中・越後は都に近い順で覚えやすい。','echi'],['kaga','加賀','かが','北陸道','石川県南部',540,220,'石川県南部。能登と対で覚える。',''],['noto','能登','のと','北陸道','石川県北部・能登半島',555,180,'能登半島を中心とする。',''],['etchu','越中','えっちゅう','北陸道','富山県',590,220,'越前と越後の間。現在の富山県。','echi'],['echigo','越後','えちご','北陸道','新潟県本州部',650,180,'「越」の三国のうち最も東。','echi'],['sado','佐渡','さど','北陸道','新潟県佐渡島',610,145,'佐渡島一島を中心とする。',''],
['tamba','丹波','たんば','山陰道','京都府中部・兵庫県中東部',420,310,'丹後と対。京都・兵庫の両府県にまたがる。','tan'],['tango','丹後','たんご','山陰道','京都府北部',395,280,'丹波から分立した北側の国。','tan'],['tajima','但馬','たじま','山陰道','兵庫県北部',365,295,'兵庫県北部。播磨・摂津などと同県内で分かれる。',''],['inaba','因幡','いなば','山陰道','鳥取県東部',330,290,'鳥取県東部。伯耆と対。',''],['hoki','伯耆','ほうき','山陰道','鳥取県西部',290,285,'難読。鳥取県西部。',''],['izumo','出雲','いずも','山陰道','島根県東部',245,285,'出雲大社で知られる。島根県東部。',''],['iwami','石見','いわみ','山陰道','島根県西部',200,300,'難読。島根県西部。',''],['oki','隠岐','おき','山陰道','島根県隠岐諸島',245,230,'隠岐諸島を中心とする島国。',''],
['harima','播磨','はりま','山陽道','兵庫県南西部',385,350,'兵庫県南西部。播州の名称にも残る。',''],['mimasaka','美作','みまさか','山陽道','岡山県北部',325,330,'難読。岡山県北部。',''],['bizen','備前','びぜん','山陽道','岡山県南東部',340,360,'備前・備中・備後の東側。','bi'],['bitchu','備中','びっちゅう','山陽道','岡山県西部',300,360,'備前三国の中央。','bi'],['bingo','備後','びんご','山陽道','広島県東部',260,360,'備前三国の西側で、現在は広島県東部。','bi'],['aki','安芸','あき','山陽道','広島県西部',220,365,'広島県西部。安芸国の宮島で知られる。',''],['suo','周防','すおう','山陽道','山口県東部',175,380,'難読。山口県東部。',''],['nagato','長門','ながと','山陽道','山口県西部',135,370,'山口県西部。周防と対。',''],
['kii','紀伊','きい','南海道','和歌山県・三重県南部',475,438,'紀州の名でも知られ、現在の県境をまたぐ。',''],['awaji','淡路','あわじ','南海道','兵庫県淡路島',395,405,'淡路島を中心とする。',''],['awa_shikoku','阿波','あわ','南海道','徳島県',360,445,'現在の徳島県。「安房」と同音なので注意。','awa'],['sanuki','讃岐','さぬき','南海道','香川県',330,410,'現在の香川県。讃岐うどんで名称が残る。',''],['iyo','伊予','いよ','南海道','愛媛県',255,440,'現在の愛媛県。',''],['tosa','土佐','とさ','南海道','高知県',300,480,'現在の高知県。',''],
['chikuzen','筑前','ちくぜん','西海道','福岡県北西部',100,420,'筑後と対。福岡県北西部。','chiku'],['chikugo','筑後','ちくご','西海道','福岡県南部',110,455,'筑前の南側。','chiku'],['buzen','豊前','ぶぜん','西海道','福岡県東部・大分県北部',150,430,'豊後と対。現在の県境をまたぐ。','bu'],['bungo','豊後','ぶんご','西海道','大分県中南部',175,465,'豊前の南側。大分県の大部分。','bu'],['hizen','肥前','ひぜん','西海道','佐賀県・長崎県本土部',60,445,'肥後と対。佐賀・長崎にまたがる。','hi'],['higo','肥後','ひご','西海道','熊本県',115,495,'現在の熊本県にほぼ対応。','hi'],['hyuga','日向','ひゅうが','西海道','宮崎県',180,510,'難読。現在の宮崎県。',''],['osumi','大隅','おおすみ','西海道','鹿児島県東部',155,545,'薩摩とともに鹿児島県本土を分ける。',''],['satsuma','薩摩','さつま','西海道','鹿児島県西部',105,540,'鹿児島県西部。薩摩藩の名称で著名。',''],['iki','壱岐','いき','西海道','長崎県壱岐島',55,400,'壱岐島を中心とする島国。',''],['tsushima','対馬','つしま','西海道','長崎県対馬',15,360,'朝鮮半島との間に位置する島国。','']
];
const P=RAW.map(a=>({id:a[0],name:a[1],reading:a[2],circuit:a[3],modern:a[4],x:a[5],y:a[6],note:a[7],family:a[8]}));
const SKILLS=['reading','kanji','mapName','nameMap','modern','circuit'];
const LABELS={reading:'読み',kanji:'漢字',mapName:'位置→国名',nameMap:'国名→位置',modern:'現在の都道府県',circuit:'五畿七道'};
const STORAGE='oldcountry68_v2',SETTINGS='oldcountry68_settings';
const MAP_OVERRIDES={tsushima:[58,760],iki:[105,790],oki:[286,642],sado:[540,535],awaji:[405,750]};
let data=loadData(),settings=JSON.parse(localStorage.getItem(SETTINGS)||'{"rateAfterChoice":false}');
let session=null,current=null,answered=false,selectedMapId=null;
function mapPoint(p){if(MAP_OVERRIDES[p.id])return MAP_OVERRIDES[p.id];return[.724884259*p.x-.0229075036*p.y+116.284111,.0422622659*p.x+1.18877382*p.y+253.291398]}
function emptySkill(){return{level:0,streak:0,due:0,seen:0,lapses:0,last:0}}
function loadData(){let d;try{d=JSON.parse(localStorage.getItem(STORAGE)||'null')}catch(e){}if(!d)d={version:2,total:0,correct:0,countries:{}};P.forEach(p=>{d.countries[p.id]??={};SKILLS.forEach(s=>d.countries[p.id][s]??=emptySkill())});return d}
function save(){localStorage.setItem(STORAGE,JSON.stringify(data))}
function saveSettings(){settings.rateAfterChoice=document.getElementById('rateAfterChoice').checked;localStorage.setItem(SETTINGS,JSON.stringify(settings))}
function avgLevel(p){return SKILLS.reduce((n,s)=>n+data.countries[p.id][s].level,0)/(SKILLS.length*5)}
function overall(){return P.reduce((n,p)=>n+avgLevel(p),0)/P.length}
function dueCount(){let now=Date.now(),n=0;P.forEach(p=>SKILLS.forEach(s=>{let x=data.countries[p.id][s];if(x.seen&&x.due<=now)n++}));return n}
function seenCountries(){return P.filter(p=>SKILLS.some(s=>data.countries[p.id][s].seen)).length}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='home')renderHome();if(id==='map')renderFreeMap();if(id==='list')renderList();if(id==='stats')renderStats()}
function renderHome(){heroDue.textContent=dueCount();heroMastery.textContent=Math.round(overall()*100)+'%';heroSeen.textContent=seenCountries()}
function startStudy(mode){session={mode,count:0,target:12};document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));study.classList.add('active');document.querySelectorAll('.bottom button').forEach(x=>x.classList.remove('active'));nextQuestion()}
function finishStudy(){session=null;go('home')}
function pickSmart(){let now=Date.now(),items=[];P.forEach(p=>SKILLS.forEach(s=>{let x=data.countries[p.id][s],due=x.seen&&x.due<=now,score=(5-x.level)*18+(due?45:0)+(x.seen?0:20)+Math.random()*12;items.push({p,s,score})}));items.sort((a,b)=>b.score-a.score);return items[0]}
function pickFor(skill){let pool=P.map(p=>({p,s:skill,x:data.countries[p.id][skill]}));pool.sort((a,b)=>{let ad=a.x.seen&&a.x.due<=Date.now()?1:0,bd=b.x.seen&&b.x.due<=Date.now()?1:0;return bd-ad||(a.x.level-b.x.level)||Math.random()-.5});return pool[0]}
function nextQuestion(){if(!session)return;if(session.count>=session.target){alert('このセットは終了です。記録に反映しました。');finishStudy();return}let item=session.mode==='smart'?pickSmart():pickFor(session.mode);current={...item};answered=false;selectedMapId=null;session.count++;renderQuestion()}
function renderQuestion(){const p=current.p,s=current.s;studyMode.textContent=session.mode==='smart'?'おすすめ復習':LABELS[session.mode];studyCount.textContent=session.count+' / '+session.target;studyProgress.style.width=((session.count-1)/session.target*100)+'%';choices.innerHTML='';studyMap.innerHTML='';studyMap.style.display='none';answerBox.classList.remove('show');rating.classList.remove('show');feedback.className='feedback';prompt.className='prompt';let q='',sub='',label='';
if(s==='reading'){label='読みを答える';q=p.name;sub='この旧国名の読みは？';renderChoices(p.reading,'reading')}
if(s==='kanji'){label='漢字を答える';q=p.reading;sub='漢字で書くと？';prompt.className='prompt reading';renderChoices(p.name,'name')}
if(s==='modern'){label='現在地を答える';q=p.name;sub='現在のおおよその都道府県は？';renderChoices(p.modern,'modern')}
if(s==='circuit'){label='五畿七道';q=p.name;sub='どの区分に属する？';renderCircuitChoices(p.circuit)}
if(s==='mapName'){label='位置から国名';q='この場所は？';sub='黄色の印で示した旧国を答える';studyMap.style.display='block';studyMap.innerHTML=mapHTML({target:p.id});renderChoices(p.name,'name')}
if(s==='nameMap'){label='国名から位置';q=p.name;sub='実際の旧国境地図上で位置をタップ';studyMap.style.display='block';studyMap.innerHTML=mapHTML({interactive:'answer'})}
questionLabel.textContent=label;prompt.textContent=q;subprompt.textContent=sub}
function distractors(p,field){let pool=P.filter(x=>x.id!==p.id);if(p.family){let f=pool.filter(x=>x.family===p.family);pool=[...f,...pool.filter(x=>x.family!==p.family)]}else{let c=pool.filter(x=>x.circuit===p.circuit);pool=[...c,...pool.filter(x=>x.circuit!==p.circuit)]}let vals=[];for(let x of pool.sort(()=>Math.random()-.5)){let v=x[field];if(!vals.includes(v)&&v!==p[field])vals.push(v);if(vals.length===3)break}return vals}
function renderChoices(correct,field){let vals=[correct,...distractors(current.p,field)].sort(()=>Math.random()-.5);choices.innerHTML=vals.map(v=>`<button class="choice" onclick='choose(this,${JSON.stringify(v)},${JSON.stringify(correct)})'>${v}</button>`).join('')}
function renderCircuitChoices(correct){let vals=[correct];['畿内','東海道','東山道','北陸道','山陰道','山陽道','南海道','西海道'].filter(x=>x!==correct).sort(()=>Math.random()-.5).slice(0,3).forEach(x=>vals.push(x));vals.sort(()=>Math.random()-.5);choices.innerHTML=vals.map(v=>`<button class="choice" onclick='choose(this,${JSON.stringify(v)},${JSON.stringify(correct)})'>${v}</button>`).join('')}
function choose(btn,value,correct){if(answered)return;answered=true;let ok=value===correct;document.querySelectorAll('#choices .choice').forEach(b=>{if(b.textContent===correct)b.classList.add('correct')});if(!ok)btn.classList.add('wrong');data.total++;if(ok)data.correct++;showAnswer(ok);if(settings.rateAfterChoice)rating.classList.add('show');else{applyResult(ok?2:0);setTimeout(nextQuestion,ok?800:1250)}}
function mapTap(ev,mode){if(mode==='answer'&&answered)return;let svg=ev.currentTarget,pt=svg.createSVGPoint();pt.x=ev.clientX;pt.y=ev.clientY;let pxy=pt.matrixTransform(svg.getScreenCTM().inverse()),best=null,bestD=1e9;P.forEach(p=>{let [x,y]=mapPoint(p),d=(x-pxy.x)**2+(y-pxy.y)**2;if(d<bestD){bestD=d;best=p}});if(!best)return;if(mode==='answer')answerMap(best.id,pxy.x,pxy.y);else openDetail(best.id)}
function answerMap(id,tapX,tapY){if(answered)return;selectedMapId=id;answered=true;let ok=id===current.p.id;data.total++;if(ok)data.correct++;let stage=document.querySelector('#studyMap .mapStage'),svg=stage?.querySelector('.mapOverlay');if(svg){let [cx,cy]=mapPoint(current.p),sel=P.find(p=>p.id===id),[sx,sy]=mapPoint(sel);svg.insertAdjacentHTML('beforeend',`<circle class="correctMark" cx="${cx}" cy="${cy}" r="18"/>${ok?'':`<circle class="wrongMark" cx="${sx}" cy="${sy}" r="14"/>`}`)}showAnswer(ok);if(settings.rateAfterChoice)rating.classList.add('show');else{applyResult(ok?2:0);setTimeout(nextQuestion,ok?1000:1650)}}
function showAnswer(ok){let p=current.p;answerMain.textContent=p.name;answerReading.textContent=p.reading;answerDetails.innerHTML=`${p.circuit} ／ ${p.modern}<br>${p.note}`;answerBox.classList.add('show');feedback.className='feedback show '+(ok?'ok':'bad');feedback.textContent=ok?'正解':'正解位置を緑、選択位置を赤で表示しました'}
function rate(r){applyResult(r);nextQuestion()}
function applyResult(r){let x=data.countries[current.p.id][current.s],now=Date.now();x.seen++;x.last=now;if(r===0){x.level=Math.max(0,x.level-1);x.streak=0;x.lapses++;x.due=now+4*60*1000}else if(r===1){x.level=Math.min(5,Math.max(1,x.level));x.streak++;x.due=now+12*60*60*1000}else if(r===2){x.level=Math.min(5,x.level+1);x.streak++;x.due=now+[0,1,2,4,8,16][x.level]*86400000}else{x.level=Math.min(5,x.level+2);x.streak++;x.due=now+[0,2,4,8,16,30][x.level]*86400000}save()}
function mapHTML(o={}){let labels=o.labels?P.map(p=>{let[x,y]=mapPoint(p);return`<text x="${x}" y="${y-14}" text-anchor="middle">${p.name}</text>`}).join(''):'';let marker='';if(o.target){let p=P.find(x=>x.id===o.target),[x,y]=mapPoint(p);marker=`<circle class="marker pulse" cx="${x}" cy="${y}" r="23"/><circle class="markerCore" cx="${x}" cy="${y}" r="7"/>`}
let click=o.interactive?`onclick="mapTap(event,'${o.interactive}')"`:'';return `<div class="mapStage"><img src="${MAP_URL}" alt="旧国境を示した日本地図" onerror="this.nextElementSibling.classList.add('show')"><div class="mapError">地図画像を読み込めませんでした。通信状態を確認して再読み込みしてください。</div><svg class="mapOverlay${o.labels?'':' hideLabels'}" viewBox="0 0 960 1003" preserveAspectRatio="xMidYMid meet" ${click}>${labels}${marker}</svg></div>`}
function renderFreeMap(){freeMap.innerHTML=mapHTML({labels:true,interactive:'detail'});labelOn.classList.add('active');labelOff.classList.remove('active')}
function setLabels(on){let svg=document.querySelector('#freeMap .mapOverlay');if(svg)svg.classList.toggle('hideLabels',!on);labelOn.classList.toggle('active',on);labelOff.classList.toggle('active',!on)}
function openDetail(id){let p=P.find(x=>x.id===id);dName.textContent=p.name;dReading.textContent=p.reading;dCircuit.textContent=p.circuit;dModern.textContent=p.modern;dNote.textContent=p.note;dMastery.textContent=Math.round(avgLevel(p)*100)+'%';dMap.innerHTML=mapHTML({target:p.id});detailModal.classList.add('show')}
function closeDetail(){detailModal.classList.remove('show')}
function openInfo(){infoModal.classList.add('show')}
function renderList(){let q=(search?.value||'').trim().toLowerCase(),c=circuitFilter?.value||'';let arr=P.filter(p=>(!c||p.circuit===c)&&(!q||[p.name,p.reading,p.modern,p.circuit].join(' ').toLowerCase().includes(q)));countryList.innerHTML=arr.length?arr.map(p=>`<button class="panel countryItem" onclick="openDetail('${p.id}')" style="text-align:left;border:1px solid var(--line)"><h3>${p.name}</h3><div class="reading">${p.reading}</div><p>${p.modern}</p><footer><span class="tag">${p.circuit}</span><span class="masteryDot">習熟 ${Math.round(avgLevel(p)*100)}%</span></footer></button>`).join(''):'<div class="empty">該当する国がありません</div>'}
function renderStats(){statAnswered.textContent=data.total;statAccuracy.textContent=data.total?Math.round(data.correct/data.total*100)+'%':'—';statMastery.textContent=Math.round(overall()*100)+'%';rateAfterChoice.checked=!!settings.rateAfterChoice;skillRows.innerHTML=SKILLS.map(s=>{let v=P.reduce((n,p)=>n+data.countries[p.id][s].level,0)/(P.length*5);return`<div class="skillRow"><div class="skillTop"><span>${LABELS[s]}</span><span>${Math.round(v*100)}%</span></div><div class="miniBar"><div style="width:${v*100}%"></div></div></div>`}).join('');let weak=[];P.forEach(p=>SKILLS.forEach(s=>{let x=data.countries[p.id][s];if(x.seen)weak.push({p,s,x,score:x.level-x.lapses*.6})}));weak.sort((a,b)=>a.score-b.score);weakList.innerHTML=weak.length?weak.slice(0,10).map(w=>`<div class="weak"><span><b>${w.p.name}</b>　${LABELS[w.s]}</span><span>Lv.${w.x.level}</span></div>`).join(''):'<div class="empty">まだ学習記録がありません</div>'}
function resetProgress(){if(confirm('学習記録をすべて初期化しますか？')){localStorage.removeItem(STORAGE);data=loadData();save();renderStats();renderHome()}}
renderHome();
